name: 'Build'

on:
  push:
    branches:    
      - '*'
      - '!main'
      - '!develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Check Types
        run: yarn check-types

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build